Update and rename build-openwrt-using-unifreq-scripts.yml to packaging-openwrt-for-qemu-etc.yml

diff --git a/.github/workflows/packaging-openwrt-for-qemu-etc.yml b/.github/workflows/packaging-openwrt-for-qemu-etc.yml
--- a/.github/workflows/packaging-openwrt-for-qemu-etc.yml
+++ b/.github/workflows/packaging-openwrt-for-qemu-etc.yml
@@ -1,10 +1,10 @@
 #=====================================================================================
-# Description: Build OpenWrt using Unifreq scripts
+# Description: Packaging OpenWrt for qemu, allwinner, rockchip and amlogic
 # Copyright (C) 2021 https://github.com/unifreq/openwrt_packit
 # Copyright (C) 2021 https://github.com/ophub/flippy-openwrt-actions
 #=====================================================================================
 
-name: Build OpenWrt using Unifreq scripts
+name: Packaging QEMU and others
 
 on:
   repository_dispatch:
@@ -21,12 +21,9 @@ on:
           - ak88
           - beikeyun
           - cm3
-          - e20c
-          - e24c
           - e25
-          - e52c
-          - e54c
           - ht2
+          - e20c
           - h28k
           - h66k
           - h68k
@@ -34,12 +31,13 @@ on:
           - h69k-max
           - h88k
           - h88k-v3
-          - jp-tvbox
           - l1pro
           - photonicat
           - qemu
           - r66s
           - r68s
+          - jp-tvbox
+          - watermelon-pi
           - rock5b
           - rock5c
           - rk3399
@@ -51,21 +49,16 @@ on:
           - s922x
           - s922x-n2
           - vplus
-          - watermelon-pi
           - zcube1-max
           - diy
       customize_rk3399:
         description: "Set customize rk3399 devices"
         required: false
-        default: "none"
-        type: choice
-        options:
-          - tvi3315a:rk3399-tvi3315a.dtb/sw799:rk3399-bozz-sw799.dtb
-          - none
+        default: "tvi3315a:rk3399-tvi3315a.dtb/sw799:rk3399-bozz-sw799.dtb"
       openwrt_kernel:
         description: "Select kernel version"
         required: false
-        default: "5.15.y_6.1.y"
+        default: "6.6.y"
         type: choice
         options:
           - 5.4.y
@@ -76,8 +69,6 @@ on:
           - 6.12.y
           - 5.4.y_5.10.y
           - 5.15.y_6.1.y
-          - 6.1.y_6.12.y
-          - 6.1.y_6.6.y
           - 6.6.y_6.12.y
       kernel_repo:
         description: "Set the kernel repository"
@@ -129,7 +120,7 @@ jobs:
         run: |
           docker rmi $(docker images -q) 2>/dev/null
           [[ -n "${AGENT_TOOLSDIRECTORY}" ]] && sudo rm -rf "${AGENT_TOOLSDIRECTORY}"
-          sudo rm -rf /usr/share/dotnet /usr/local/lib/android 2>/dev/null
+          sudo rm -rf /usr/share/dotnet /etc/apt/sources.list.d /usr/local/lib/android 2>/dev/null
           sudo swapoff -a
           sudo rm -f /swapfile /mnt/swapfile
           sudo -E apt-get -y update
@@ -167,35 +158,34 @@ jobs:
         working-directory: /builder
         if: ${{ steps.init.outputs.status }} == 'success' && !cancelled()
         run: |
-          armsr_tarfile_repo="ophub/amlogic-s9xxx-openwrt"
+          armvirt_tarfile_repo="ophub/amlogic-s9xxx-openwrt"
           releases_tag_keywords="OpenWrt_lede_"
 
-          armsr_tarfile_path="openwrt/output"
-          [[ -d "${armsr_tarfile_path}" ]] || mkdir -p ${armsr_tarfile_path}
+          armvirt_tarfile_path="openwrt/output"
+          [[ -d "${armvirt_tarfile_path}" ]] || mkdir -p ${armvirt_tarfile_path}
           ln -sf /builder/openwrt ${GITHUB_WORKSPACE}/openwrt
 
-          latest_version=$(curl -s \
-                -H "Accept: application/vnd.github+json" \
-                -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-                https://api.github.com/repos/${armsr_tarfile_repo}/releases?per_page=100 | \
-                jq -r --arg RTK "${releases_tag_keywords}" \
-                --arg BOARD "-rootfs.tar.gz" \
-                '[.[] | select(.tag_name | contains($RTK))] |
-                map(.assets[] | select(.browser_download_url | endswith($BOARD))) |
-                sort_by(.updated_at) |
-                reverse |
-                .[0] |
-                {data: .updated_at, url: .browser_download_url}')
+          latest_version="$(curl -s \
+                              -H "Accept: application/vnd.github+json" \
+                              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+                              https://api.github.com/repos/${armvirt_tarfile_repo}/releases?per_page=100 |
+                              jq '.[]' |
+                              jq -s --arg RTK "${releases_tag_keywords}" '.[] | select(.tag_name | contains($RTK))' |
+                              jq -s '.[].assets[] | {data:.updated_at, url:.browser_download_url}' |
+                              jq -s --arg BOARD "-rootfs.tar.gz" '.[] | select(.url | endswith($BOARD))' |
+                              jq -s 'sort_by(.data)|reverse[]' |
+                              jq -s '.[0]' -c
+                          )"
 
-          [[ -z "${latest_version}" || "${latest_version}" == "null" ]] && echo "Invalid OpenWrt rootfs download address." && exit 1
+          [[ "${latest_version}" == "null" ]] && echo "Invalid OpenWrt rootfs download address." && exit 1
           latest_updated_at="$(echo ${latest_version} | jq -r '.data')"
           latest_url="$(echo ${latest_version} | jq -r '.url')"
 
           openwrt_filename="${latest_url##*/}"
-          curl -fsSL "${latest_url}" -o "${armsr_tarfile_path}/${openwrt_filename}"
+          curl -fsSL "${latest_url}" -o "${armvirt_tarfile_path}/${openwrt_filename}"
           [[ "${?}" -ne "0" ]] && echo "Invalid OpenWrt rootfs download address." && exit 1
 
-          echo "build_tag=OpenWrt_armv8_${{ inputs.openwrt_storage }}_$(date +"%Y.%m")" >> ${GITHUB_OUTPUT}
+          echo "build_tag=OpenWrt_aarch64_${{ inputs.openwrt_storage }}_$(date +"%Y.%m")" >> ${GITHUB_OUTPUT}
           echo "status=success" >> ${GITHUB_OUTPUT}
 
       - name: Clone packit source code
@@ -212,7 +202,7 @@ jobs:
         uses: ophub/flippy-openwrt-actions@main
         if: ${{ steps.down.outputs.status }} == 'success' && !cancelled()
         env:
-          OPENWRT_ARMSR: openwrt/output/*rootfs.tar.gz
+          OPENWRT_ARMVIRT: openwrt/output/*rootfs.tar.gz
           SELECT_PACKITPATH: openwrt_packit
           PACKAGE_SOC: ${{ inputs.openwrt_soc }}
           CUSTOMIZE_RK3399: ${{ inputs.customize_rk3399 }}
